version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Set the root password
      MYSQL_DATABASE: mydatabase         # Set the name of the database
      MYSQL_USER: myuser                 # Create a new user
      MYSQL_PASSWORD: mypassword         # Set the password for the new user
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"  # Map MySQL container to a different port on the host
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    entrypoint: ["./wait-for-it.sh", "mysql:3306", "--", "java", "-jar", "/app/app.jar"]

volumes:
  mysql_data: